# Configure global settings in this section.
global:
  name: usc1-consul
  enabled: true
  datacenter: usc1-dc1
  # Bootstrap ACLs within Consul. This is highly recommended.
  acls:
    manageSystemACLs: true
  # Gossip encryption
  gossipEncryption:
    autoGenerate: true
# Configure your Consul servers in this section.
server:
  # Specify three servers that wait until all are healthy to bootstrap the Consul cluster.
  replicas: 3
  # Specify the resources that servers request for placement. These values will serve a large environment.
  resources:
    requests:
      memory: '5Gi'
      cpu: '4'
      disk: '15Gi'
    limits:
      memory: '5Gi'
      cpu: '4'
      disk: '15Gi'
  # If using Enterprise, reference the Kubernetes secret that holds your license here
  enterpriseLicense: ""
# Configure Consul clients in this section
client:
  # Specify the resources that clients request for deployment.
  resources:
    requests:
      memory: '5Gi'
      cpu: '2'
      disk: '15Gi'
    limits:
      memory: '5Gi'
      cpu: '2'
      disk: '15Gi'
# Enable and configure the Consul UI.
ui:
  enabled: true
# Enable Consul connect pod injection
connectInject:
  enabled: true
  default: true
controller:
  enabled: true
